modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/Heads/issues"
license="MIT"

[[mods]]
modId="heads"
version="${file.jarVersion}"
displayName="Heads"
displayURL="https://www.curseforge.com/minecraft/mc-mods/heads"
authors="Mrbysco"
description='''
Adds more mob heads to the game
'''
[[dependencies.heads]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"
[[dependencies.heads]]
modId="forge"
mandatory=true
versionRange="[40.0.24,)"
ordering="NONE"
side="BOTH"