modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Heads/issues"
license="MIT"

[[mods]]
modId="heads"
version="${file.jarVersion}"
displayName="Heads"
displayURL="https://www.curseforge.com/minecraft/mc-mods/heads"
authors="Mrbysco"
description='''
Adds more mob heads to the game
'''
[[dependencies.heads]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.heads]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"