modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/Heads/issues"
license="MIT"

[[mods]]
modId="heads"
version="${file.jarVersion}"
displayName="Heads"
displayURL="https://www.curseforge.com/minecraft/mc-mods/heads"
authors="Mrbysco"
description='''
Adds more mob heads to the game
'''
[[dependencies.heads]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.heads]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"